name: Update Project Field Based on Label
on:
  issues:
    types:
      - labeled

jobs:
  update_project_field:
    runs-on: ubuntu-latest
    steps:
      - name: Update Project Field
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LABEL=${{ github.event.label.name }}
          ISSUE_NODE_ID=${{ github.event.issue.node_id }}

          # Map labels to project field option IDs
          if [ "$LABEL" = ""Severity 1 - Bug"" ]; then
            OPTION_ID="269d0976"
          elif [ "$LABEL" = "p2" ]; then
            OPTION_ID="<OPTION_ID_FOR_P2>"
          else
            exit 0
          fi

          # Update the project field using the GraphQL API
          curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            --data '{"query":"mutation { updateProjectV2ItemFieldValue(input: { projectId: \"2\", itemId: \"$ISSUE_NODE_ID\", fieldId: \"150598072\", value: { singleSelectOptionId: \"$OPTION_ID\" }}) { projectV2Item { id }}}"}' \
            https://api.github.com/graphql
