name: Update Project Field Based on Label
on:
  issues:
    types:
      - labeled
jobs:
  update_project_field:
    runs-on: ubuntu-latest
    steps:
      - name: Update Project Field
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        run: |
          LABEL="Severity 1 - Bug"
          ISSUE_NODE_ID="I_kwDONSxMlc6gevBq"
          
          # Map labels to project field option IDs
          if [ "$LABEL" = "Severity 1 - Bug" ]; then
            OPTION_ID="269d0976"
          elif [ "$LABEL" = "p2" ]; then
            OPTION_ID="<OPTION_ID_FOR_P2>"
          else
            exit 0
          fi
          
          # Debugging-Ausgabe
          echo "ISSUE_NODE_ID is: $ISSUE_NODE_ID"
          echo "OPTION_ID is: $OPTION_ID"
          
          # Update the project field using the GraphQL API
          curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            --data "{\"query\":\"mutation { updateProjectV2ItemFieldValue(input: { projectId: \\\"PVT_kwHOBLqZMc4As--D\\\", itemId: \\\"$ISSUE_NODE_ID\\\", fieldId: \\\"PVTSSF_lAHOBLqZMc4As--Dzgj58bg\\\", value: { singleSelectOptionId: \\\"$OPTION_ID\\\" }}) { projectV2Item { id }}}\"}" \
            https://api.github.com/graphql
