name: Update Project Status

on:
  issues:
    types:
      - labeled

jobs:
  update-project-status:
    if: contains(github.event.label.name, 'Severity 1 - Bug') # Nur ausführen, wenn das Label "feature" hinzugefügt wurde
    runs-on: ubuntu-latest
    steps:
      - name: Set project status to "Severity 1 - Bug"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Projekt-ID und Spalten-ID definieren
          PROJECT_ID="2" # Ersetzen Sie dies mit der ID Ihres Projekts
          COLUMN_ID="2"   # Ersetzen Sie dies mit der ID der Zielspalte (z. B. "Feature")

          # Issue-ID abrufen
          ISSUE_ID=$(gh issue view ${{ github.event.issue.number }} --json id --jq '.id')

          # Issue in die entsprechende Spalte verschieben
          curl -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/projects/columns/$COLUMN_ID/cards \
            -d '{"content_id": '"$ISSUE_ID"', "content_type": "Issue"}'
